CoreAndFood/Models/Food.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreAndFood.Models
{
    public class Food
    {
        public int FoodID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageURL { get; set; }
        public int Stock { get; set; }
        public int CategoryID { get; set; }
        public virtual Category Category { get; set; }
    }
}

CoreAndFood/Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreAndFood.Repositories;
using CoreAndFood.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;

namespace CoreAndFood.Controllers
{
    public class FoodController : Controller
    {
        Context c = new Context();
        FoodRepository foodRepository = new FoodRepository();
        public IActionResult Index(int page = 1)
        {
            return View(foodRepository.TList("Category").ToPagedList(page,3));            
        }
        [HttpGet]
        public IActionResult FoodAdd()
        {
            List<SelectListItem> values = (from x in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();
            ViewBag.v1 = values;
            return View();
        }
        [HttpPost]
        public IActionResult FoodAdd(Food p)
        {
            foodRepository.TAdd(p);
            return RedirectToAction("Index");
        }
        public IActionResult FoodDelete(int id)
        {
            foodRepository.TDelete(new Food { FoodID = id });
            return RedirectToAction("Index");
        }
        public IActionResult FoodGet(int id)
        {
            var x = foodRepository.TGet(id);
            Food f = new Food()
            {
                CategoryID = x.CategoryID,
                Name = x.Name,
                Price = x.Price,
                Stock=x.Stock,                
                Description = x.Description,
                ImageURL=x.ImageURL,
                FoodID = x.FoodID
            };
            return View(f);
        }
        [HttpPost]
        public IActionResult FoodUpdate(Food p)
        {
            var x = foodRepository.TGet(p.FoodID);
            x.CategoryID = p.CategoryID;
            x.Name = p.Name;
            x.Price = p.Price;
            x.Stock = p.Stock;
            x.Description = p.Description;
            x.ImageURL = p.ImageURL;
            x.FoodID = p.FoodID;
            foodRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
    }
}

CoreAndFood/Views/Food/FoodAdd.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model CoreAndFood.Models.Food;

@{
    Layout = "~/Views/Shared/_LayoutTest.cshtml";
}
<h2>Food Add Page</h2>
<br />
@using (Html.BeginForm("FoodAdd", "Food", FormMethod.Post))
{
    @Html.LabelFor(x => x.Name)
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Stock)
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Price)
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ImageURL)
    @Html.TextBoxFor(x => x.ImageURL, new { @class = "form-control" })
    <br />
    @Html.Label("Category")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Description)
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Save</button>
}

CoreAndFood/Views/Food/FoodGet.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model CoreAndFood.Models.Food;

@{
    Layout = "~/Views/Shared/_LayoutTest.cshtml";
}
<h2>Food Update Page</h2>
<br />
@using (Html.BeginForm("FoodUpdate", "Food", FormMethod.Post))
{
    @Html.LabelFor(x => x.FoodID)
    @Html.TextBoxFor(x => x.FoodID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Name)
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Stock)
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Price)
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ImageURL)
    @Html.TextBoxFor(x => x.ImageURL, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CategoryID)
    @Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" })
    <br />
    @*@Html.Label("Category")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control" })
        <br />*@
    @Html.LabelFor(x => x.Description)
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Save</button>
}

CoreAndFood/Views/Food/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

@model IPagedList<CoreAndFood.Models.Food>
@{
    Layout = "~/Views/Shared/_LayoutTest.cshtml";
}
<h2>Food List</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Food Name</th>
        <th>Category Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Delete</th>
        <th>Update</th>
        <th>Details</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.FoodID</td>
            <td>@item.Name</td>
            <td>@item.Category.CategoryName</td>
            <td>@item.Price</td>
            <td>@item.Stock</td>
            <td><a href="/Food/FoodDelete/@item.FoodID/" class="btn btn-danger">Delete</a></td>
            <td><a href="/Food/FoodGet/@item.FoodID/" class="btn btn-success">Update</a></td>
            <td><a href="#" class="btn btn-info">Details</a></td>
        </tr>

    }
</table>
<div class="pull-right">
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index",
       new
            {
                page

     }),
     new PagedListRenderOptions
     {
         LiElementClasses = new string[] { "page-item" },
         PageClasses = new string[] { "page-link" },
         Display = PagedListDisplayMode.IfNeeded

          })
</div>

<a href="/Food/FoodAdd/" class="btn btn-primary">New Food</a>